### ISSUE TITLE
Feature request: Music albums

### ISSUE THREAD

**Issue by Kullenej** [mProjectsCode/obsidian-media-db-plugin#1]
Please add music albums as well. I know that Rovi has an API, but I think the most common used is MusicBrainz.

**Comment by mProjectsCode** [comment]
Possible APIs after a bit of searching:
- https://github.com/Borewit/musicbrainz-api
- https://ytmusicapi.readthedocs.io/en/latest/index.html

**Comment by Kullenej** [comment]
Great! I think I would go for the MusicBrainz API. Just a feeling from scourging the internet for this.

**Comment by mProjectsCode** [comment]
implemented with commit 003c568099aa79edb97285331870c13c9b302fc6
