### ISSUE TITLE
Copy resulting YAML to clipboard instead of creating a file

### ISSUE THREAD

**Issue by redactedscribe** [mProjectsCode/obsidian-media-db-plugin#107]
**Is your feature request related to a problem? Please describe.**
I would prefer to copy the YAML to the clipboard instead of creating any file.

**Describe the solution you'd like**
A copy to clipboard button after selecting one of the results.

Thanks.

**Comment by ltctceplrm** [comment]
This option now exists natively in obsidian if you look at the bottom of the YAML preview screen. So I think the issue can be closed as solved?
![](https://i.imgur.com/hYmdcYS.png)
