### ISSUE TITLE
Nothing rendered in Preview Modal

### ISSUE THREAD

**Issue by gamephreak13** [mProjectsCode/obsidian-media-db-plugin#111]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**Describe the bug**
The preview modal only displays dataviewjs errors.

**To Reproduce**

1. Go to 'add Media DB Entry (game)'
2. Search 'Roadwarden'
3. Scroll down to 'Roadwarden'
4. Preview Modal displays dataviewjs error blocks.

**Expected behavior**
A preview of how the note will look

**Screenshots**
![image](https://github.com/mProjectsCode/obsidian-media-db-plugin/assets/31524849/87208acc-af10-478c-b60a-953b6b62d6b3)

**Occurs on**

-   [x] Windows

**Plugin version**
0.5.2

**Additional context**
I am using the templates provided by mProjectsCode.

**Comment by mProjectsCode** [comment]
i am passing an empty string as the file path to the markdown render function (as recommended by the obsidian devs), since there isn't a file for this content yet. I guess dataview does not like that and errors out. There is nothing i can do about this.
