### ISSUE TITLE
Moby Games API

### ISSUE THREAD

**Issue by gamephreak13** [mProjectsCode/obsidian-media-db-plugin#118]
**Name**
Moby Games

**Link**
[A link to their API documentation](https://www.mobygames.com/info/api/)

**What does the API do/offer**
Moby Games has one of the largest video game databases that is updated with video games from all stores, not just steam.

-   [/] Is the API free to use
    - If you have an account you can get a personal API key
    - They also have a blurb about commercial API keys but that seems a bit overkill for this use-case
-   [x] Does the API require authentication
    - Technically yes, since the API key is tied to a personal account. 
    - It doesn't require it's own authorization piece since it's just done via the passed in URL

**Comment by Aparikk** [comment]
This would be a very nice addition. SteamDB misses Alan Wake 2 e.g. since it's on Epic only and OMDB misses many games generally.

**Comment by miguelandres** [comment]
When is a new release with this coming out? i was looking exactly for a way to add playstation games that are not in OMDB and noticed the docs mention support for this API but the latest release is from before it was added.
