### ISSUE TITLE
Toggle to automatically open newly created Media DB entry

### ISSUE THREAD

**Issue by deafmute1** [mProjectsCode/obsidian-media-db-plugin#123]
**Is your feature request related to a problem? Please describe.**
I use mediadb to track some basic info about status of completion using 4 checkboxes that I've added to all the properties of Media DB notes via the custom template option. Most of the time I want to change the status of a newly added item, and so nearly every time I make an item I open it. It would be nice to save a bit of time by automatically opening it.

**Describe the solution you'd like**
Toggle box in settings called something like "Open newly created entry", could also have drop down with options like "In new tab", "In current tab". This would open the media db entry upon its creation.

**Additional context**

**Comment by kelszo** [comment]
Do you mind if I fix this @mProjectsCode?

**Comment by mProjectsCode** [comment]
go ahead :)
