### ISSUE TITLE
Manga plot property is broken

### ISSUE THREAD

**Issue by Nitero** [mProjectsCode/obsidian-media-db-plugin#124]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**Describe the bug**
When importing the manga "Omniscient Reader (2020)" the note is broken and displays the frontmatter in red.
The issue seems to be that only the first quotation mark in the plot property is properly escaped with a backslash: `\"scenarios"`

**To Reproduce**

1. Have the setting "Add optional quotation marks around strings in the metadata block" enabled (default)
2. Click on "Add new Media DB entry"
3. Enable "MALAPI Manga"
4. Import "Omniscient Reader (2020)"
5. See error

**Expected behavior**
the media to import without errors

**Screenshots**
![image](https://github.com/mProjectsCode/obsidian-media-db-plugin/assets/11302557/cbe29c11-b715-4079-96e4-57015466c901)

**Occurs on**

-   [x] Windows
-   [ ] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.6.0

**Additional context**
-

**Comment by mProjectsCode** [comment]
Fix is merged
