### ISSUE TITLE
Add index operator for arrays when templating

### ISSUE THREAD

**Issue by kelszo** [mProjectsCode/obsidian-media-db-plugin#127]
**Is your feature request related to a problem? Please describe.**
The `author`, `director`, `artists`, and etc fields can have more than 1 item. But when deciding on a file name, usually one only wants to use the first item. For example: some books include the translators, preface authors, and etc in the author field.

Example from openlibrary: https://openlibrary.org/works/OL21095839W/Doctor_Glas

**Describe the solution you'd like**
Add support for `{{ FIRST:variable_name }}` and `{{ LAST:variable_name }}` for indexing arrays.

**Comment by kelszo** [comment]
I can create a PR if you agree that this is a good addition

**Comment by mProjectsCode** [comment]
Sounds good :)
