### ISSUE TITLE
tags in Book template get overwritten by plugin

### ISSUE THREAD

**Issue by wealthychef1** [mProjectsCode/obsidian-media-db-plugin#136]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**Describe the bug**
I am using a template for MediaDB Books queries.  
When I search a book, the tag gets omitted.  

````markdown
---
aliases: 
tags:
  - books/notes/mine
cssclasses:
  - centerImg
desire: 
recommender: 
plot: test plot
something:
  - else
---
# Book Template

## Document Info
- created:: <% "[[" + tp.date.now("YYYY-MM-DD") + "]]" %> 
- modified:: <% "`=this.file.mtime`" %>
- These are my freehand notes.  
- For auto-generated annotations, see <% "[[Knowledge/Books, Programs and People/ibook/" + tp.file.title + "]]" %>

## Overview 

## My Book Notes

````

**To Reproduce**
- copy my template or put tags in any template you are using with MediaDB
- execute a search
- the tag will be replaced with "MediaDB/book" or whatever. 

**Expected behavior**
I'm hoping that "mediaDB/book" gets appended to my tags in my template.  

**Screenshots**
This movie demonstrates the behavior with my template.  

![2024-03-17 15 32 40 CleanShot Obsidian](https://github.com/mProjectsCode/obsidian-media-db-plugin/assets/4825448/b3a3166d-7824-4a82-8f58-45ab3e1879b4)

**Occurs on**

-   [ ] Windows
-   [x] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.6.0

**Additional context**

**Comment by ltctceplrm** [comment]
The best solution for this is to disable the default tags for books in MediaDB and only use your own template for the tags
![image](https://github.com/mProjectsCode/obsidian-media-db-plugin/assets/14954927/25563863-e85d-4690-ba83-c6f1794ea28c)
I do this for the properties that I want more control over and it works great.
```
tags:
  - books/notes/mine
  - MediaDB/book
```

**Comment by wealthychef1** [comment]
OK that will work!  Thanks
