### ISSUE TITLE
OMDB series not showing up in series search results on iOS

### ISSUE THREAD

**Issue by BrianBatchelder** [mProjectsCode/obsidian-media-db-plugin#151]
-   [X] The Plugin is up to date
-   [X] Obsidian is up to date

**Describe the bug**
When I search for "The Boys" on my Mac using advanced search and OMDbAPI, the series is found. When I do the same on iOS, nothing is found. OMDbAPI key is present in both settings.

**To Reproduce**
Do as described.

**Expected behavior**
The series should be found regardless of compute platform.

**Screenshots**

**Occurs on**

-   [ ] Windows
-   [ ] macOS
-   [ ] Linux
-   [ ] Android
-   [X] iOS

**Plugin version**
0.7.0

**Additional context**

**Comment by BrianBatchelder** [comment]
I was able to get the following from the iOS console:

> [Log] editing toolbar disable loading on mobile (x2)
[Debug] MDB | advencedSearchModal closed with code 0
[Debug] MDB | api manager queried with "The boys "
[Log] MDB | api "OMDbAPI" queried by Title
[Error] Failed to load resource: The resource could not be loaded because the App Transport Security policy requires the use of a secure connection. (www.omdbapi.com, line 0) (http://www.omdbapi.com/?s=The%20boys%20&apikey=74c8af7b)
[Warning] TypeError: Load failed

If you google "The resource could not be loaded because the App Transport Security policy requires the use of a secure connection", you'll find lots of hits, like [this](https://stackoverflow.com/questions/32631184/the-resource-could-not-be-loaded-because-the-app-transport-security-policy-requi) one. Most probably won't solve your problem, as they are app-level settings. You'll probably just have to use https:

**Comment by mProjectsCode** [comment]
the current dev version already uses https, but I forgot to release it

**Comment by mProjectsCode** [comment]
should be fixed in `0.7.1`

**Comment by BrianBatchelder** [comment]
Confirmed. Fixed in 0.7.1
