### ISSUE TITLE
Import errors referencing 'undefined' metadata missing

### ISSUE THREAD

**Issue by jimazing** [mProjectsCode/obsidian-media-db-plugin#168]
Obsidian Version v1.6.7
MediaDB Version 0.7.2

I love this plugin. Adding items one at a time works beautifully. Thank you.

Problem: I have hundreds of items already in Obsidian that I want to import into MediaDB. When I run the import against my Books folder, every item generates this error: "metadata field 'undefined' not found or empty"

- There is no metadata named "undefined"
- I have a title set for each of the books.

**Comment by ltctceplrm** [comment]
I suspect that you forgot to specify which metadata field you want to use for the search:
This image shows the field to be empty but proposes to use `title`
![image](https://github.com/user-attachments/assets/76ec8368-ce06-44b1-8818-889a8d35c8bb)

In this image I wrote `title` as the metadata field to be used
![image](https://github.com/user-attachments/assets/2f32d681-a4e8-426a-8480-a5cfb21cc382)

If it still doesn't work could you share a copy of the yaml for one of your book notes?

**Comment by jimazing** [comment]
Thank you! That was it. 

The word "title" is in the box, but it appears lighter.  I assumed I didn't need to enter a value. Now I see it was a suggested value. It was confusing me.
