### ISSUE TITLE
metadata field customization

### ISSUE THREAD

**Issue by GarDrastic** [mProjectsCode/obsidian-media-db-plugin#19]
User settings to customize the metadata field names would be a nice feature.

Example, the "personalRating" field I'd like to be able to change to just "rating" for consistency with my existing media review notes. I've also noticed when pulling movie data from OMDB API, it's assigning a "producer" field that's more rightly "director" and configurable customization of fields would address that.

**Comment by mProjectsCode** [comment]
I also thought about that, but it would require a bigger rewrite.

But this is a thing I want to implement in the future.
