### ISSUE TITLE
Templates - existing frontmatter

### ISSUE THREAD

**Issue by isle9** [mProjectsCode/obsidian-media-db-plugin#33]
- [x] The Plugin is up to date
- [x] Obsidian is up to date

**Describe the bug**
The plugin doesn't take into account existing frontmatter in templates.

**To Reproduce**
1. Add existing frontmatter to your templates.
2. Import an a movie/game etc. trough the plugin.
3. The plugin will create it's own frontmatter encapsulated inside the two `---` and the existing frontmatter will be rendered as markdown outside of the frontmatter.

**Expected behavior**
I expected the plugin to take into account existing frontmatter and only to add new entries.

**Screenshots**
![image](https://user-images.githubusercontent.com/74906541/175007732-08e7fed0-0a83-41f4-9d89-54dc2059d86f.png)

**Occurs on**
- [x] Windows
- [ ] macOS
- [ ] Linux
- [ ] Android
- [ ] iOS

**Plugin version**
0.3.0

**Comment by mProjectsCode** [comment]
Yes, that is a side effect of how templates currently work, but I will try to fix this the next few days

**Comment by mProjectsCode** [comment]
should be fixed in release `0.3.1`
