### ISSUE TITLE
Own custom props

### ISSUE THREAD

**Issue by Shirobachi** [mProjectsCode/obsidian-media-db-plugin#34]
**Is your feature request related to a problem? Please describe.**
I would like be able to set up new props in template, like in my case season and episode. I know I can use `episode::0` but I think this is styleless.

**Describe the solution you'd like**
Maybe some mapping or somehow in template would work fine

**Additional context**
Thanks for your plugin! <3

**Comment by mProjectsCode** [comment]
same underlying issue as #33

**Comment by Shirobachi** [comment]
Thanks and sorry, love your product! <3

**Comment by mProjectsCode** [comment]
should be fixed in release `0.3.1`
