### ISSUE TITLE
Add a command option per category: add a movie, add a game, add a wikipedia info

### ISSUE THREAD

**Issue by tecnoborder** [mProjectsCode/obsidian-media-db-plugin#38]
Hello there,
the plugin is amazing but I would like to have specific commands per each category (e.g. movie), without having to select every time in the pop-up windows which database to query. Also, a pre-defined selection mode of the database to query (e.g. only Wikipedia) would save a lot of time.

**Comment by tecnoborder** [comment]
this is relevant as I use the rewarder plugin and every time I select a database I got a reward. Having the possibility to have a combined search with a preferred list of databases would make the data entry more straightforward.

**Comment by mProjectsCode** [comment]
This will be done as part of the new simple search modal #54 hopefully in october
