### ISSUE TITLE
Using a template to get a timestamp gives an error

### ISSUE THREAD

**Issue by ltctceplrm** [mProjectsCode/obsidian-media-db-plugin#44]
- [X] The Plugin is up to date
- [X] Obsidian is up to date

**Describe the bug**
When I try to timestamp the new media entries using the templates they give an error instead of the timestamp.

**To Reproduce**
1. Have this this template for movies `created: {{ date:YYYY-MM-DDTHH:mm:ssZ }}`
2.  Add a new media DB movie entry
3. See error
> created:
>     "{ INVALID TEMPLATE TAG }": null

**Expected behavior**
For regular notes this template works fine and it should post the timestamp like this:
> created: 2022-08-20T23:46:58+02:00

**Occurs on**
- [x] Windows

**Plugin version**
0.3.1

**Additional context**
I've also tried the following templates with little success:
`created: {{ date }}`
>created:
>   "{ INVALID TEMPLATE TAG - object undefined }": null
  
Or

`created: {{date:YYYY-MM-DDTHH:mm:ssZ}}` , `created: {{ date : YYYY-MM-DDTHH:mm:ssZ }}`

I'm not sure if it is a bug though or if I'm just doing something wrong

**Comment by ltctceplrm** [comment]
If I use the Templater plugin to add the timestamp with `<% tp.date.now("YYYY-MM-DD[T]HH:mm:ssZ") %>` instead of using the Obsidian template then it actually works, weird

**Comment by mProjectsCode** [comment]
it is probably because of the extra `:` in there

**Comment by ltctceplrm** [comment]
Oh, which `:` should I remove to have it work with the default template?

**Comment by mProjectsCode** [comment]
try removing the ones in the date template

**Comment by ltctceplrm** [comment]
Oh okay, I'll continue using templater in the meantime since then the timestamp does work.
