### ISSUE TITLE
An option for only updating the YAML and keeping the note content intact

### ISSUE THREAD

**Issue by ltctceplrm** [mProjectsCode/obsidian-media-db-plugin#49]
**Is your feature request related to a problem? Please describe.**
I use mediaDB to create notes about movies which I then fill up with a review or my thoughts of the movie in the body of the note, if I run command to update the note then it erases everything I wrote about the movie and only keeps the YAML.

**Describe the solution you'd like**
I think adding an option to only update the YAML would make the most sense, of course user modified YAML like date watched or user score would still be kept as well.

**Comment by AB1908** [comment]
Hmm I think I know how to do this but it's now my computer that's borked. I'll look at it next week in case the author is fine with me tackling it.

**Comment by mProjectsCode** [comment]
sure go for it @AB1908, I would have done it today, but then I will start work on #48

**Comment by ltctceplrm** [comment]
Damn that's a quick fix, thank you. I'm looking forward to try it out in the next release, this plugin really saves me a lot of time.

**Comment by mProjectsCode** [comment]
The next release will take some time, I am currently aiming for early October
