### ISSUE TITLE
Preview for importing data in the select modal

### ISSUE THREAD

**Issue by mProjectsCode** [mProjectsCode/obsidian-media-db-plugin#53]

**Comment by mProjectsCode** [comment]
could make it a button press to load a preview
already update the elements within the select modal
add a property to models indicating that details have been queried 
on import only query the details of those that are missing

**Comment by mProjectsCode** [comment]
(those are just quick notes for my future self)

**Comment by AB1908** [comment]
A very rudimentary preview modal:
![image](https://user-images.githubusercontent.com/14124383/194709143-1477859b-2c44-49a5-a7a3-3a6d73c361f5.png)

**Comment by mProjectsCode** [comment]
Looks nice, i just need to fix all the styling issues once I have access to `v0.16.x`
