### ISSUE TITLE
Problems with new update introduced in #50

### ISSUE THREAD

**Issue by mProjectsCode** [mProjectsCode/obsidian-media-db-plugin#56]
> There are some problems with this, the new lines were needed sometimes and it doubles the template. (See image)

![image](https://user-images.githubusercontent.com/61602848/192292818-5b979837-ba40-47ec-91aa-178ae53be9a8.png)

_Originally posted by @mProjectsCode in https://github.com/mProjectsCode/obsidian-media-db-plugin/issues/50#issuecomment-1258068193_

**Comment by AB1908** [comment]
Interesting. I'll take a look now that my PC is back up and running sooner than expected. Thanks for flagging this.

**Comment by mProjectsCode** [comment]
Congrats on your pc working again. 

Maybe you could do two versions, one like the original (updating the entire note) and one that just updates the metadata.

**Comment by AB1908** [comment]
I'm considering writing a test and rewriting it to use `app.vault.modify` since I think it feels a little extra to delete and recreate the note (wonder if we lose version history this way).

**Comment by mProjectsCode** [comment]
Valid point, i did it with delete and recreate because the name might change. E.g. the name of the item in the API could change or the user could have changed the file name template, but I guess you can fix that by renaming it.

**Comment by AB1908** [comment]
I can't repro this. Can you paste some example content?

**Comment by mProjectsCode** [comment]
Have a template with content e.g.:
```
This is a test template.
```

Import a new entry (movie in my case) results in:
```
---
type: "movie"
subType: null
title: "Star Wars: Episode IV - A New Hope"
englishTitle: "Star Wars: Episode IV - A New Hope"
year: "1977"
dataSource: "OMDbAPI"
url: "https://www.imdb.com/title/tt0076759/"
id: "tt0076759"
genres: 
  - "Action"
  - "Adventure"
  - "Fantasy"
producer: "George Lucas"
duration: "121 min"
onlineRating: 8.6
image: "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg"
released: true
premiere: "5/25/1977"
watched: false
lastWatched: ""
personalRating: 0
tags: "#mediaDB/tv/movie"
---This is a test template.
```
Note the missing empty line between the frontmatter block and the template.

Update the note once:
```
---
type: "movie"
subType: null
title: "Star Wars: Episode IV - A New Hope"
englishTitle: "Star Wars: Episode IV - A New Hope"
year: "1977"
dataSource: "OMDbAPI"
url: "https://www.imdb.com/title/tt0076759/"
id: "tt0076759"
genres: 
  - "Action"
  - "Adventure"
  - "Fantasy"
producer: "George Lucas"
duration: "121 min"
onlineRating: 8.6
image: "https://m.media-amazon.com/images/M/MV5BOTA5NjhiOTAtZWM0ZC00MWNhLThiMzEtZDFkOTk2OTU1ZDJkXkEyXkFqcGdeQXVyMTA4NDI1NTQx._V1_SX300.jpg"
released: true
premiere: "5/25/1977"
watched: null
lastWatched: null
personalRating: null
tags: "#mediaDB/tv/movie"
---This is a test template.This is a test template.
```
Note there being two templates and missing empty lines.

**Comment by AB1908** [comment]
Ah I didn't do template testing. Thanks for the heads up.

**Comment by AB1908** [comment]
Sorry for not picking this up, I've been busy with my SRS rewrite and some other stuff haha.

**Comment by mProjectsCode** [comment]
no problem
