### ISSUE TITLE
Specify file location for different media types

### ISSUE THREAD

**Issue by TaardeT** [mProjectsCode/obsidian-media-db-plugin#57]
It would be great to place different media entries in different folders (movie in movies folder, etc)

**Comment by simzdk** [comment]
Agree. I am missing this feature as well.

**Comment by mProjectsCode** [comment]
I will try to do this tomorrow

**Comment by mProjectsCode** [comment]
> I will try to do this tomorrow

well today is not tomorrow xD, but it has been implemented
