### ISSUE TITLE
Shouldn't have to scroll the entire search modal to hit submit/ok

### ISSUE THREAD

**Issue by AB1908** [mProjectsCode/obsidian-media-db-plugin#58]
I want to be able to select the first result and then hit submit instead of scrolling through the entire thing. Will open a PR.

**Comment by mProjectsCode** [comment]
wdym? can you elaborate on the issue? the buttons should not be off screen

**Comment by mProjectsCode** [comment]
![image](https://user-images.githubusercontent.com/61602848/194544419-27f20014-90f5-442e-aaa5-76189787c9f2.png)
the scroll bar in only in the results, so the buttons are visible all the time.
You can even focus the buttons using tab
(talking about the O_O branch here, this might be different on master or the current release)

**Comment by AB1908** [comment]
Huh might be a case of me breaking something.
![image](https://user-images.githubusercontent.com/14124383/194544826-31970cc5-9f2a-47c4-89c1-d7fcbec7917b.png)

**Comment by AB1908** [comment]
You can ignore this issue for now. I'll change some stuff and test later.

**Comment by mProjectsCode** [comment]
hmmm, is this on your own branch?

**Comment by AB1908** [comment]
Nah I just checked out the O_O branch and was looking around for the new changes and where I should start digging.

**Comment by AB1908** [comment]
Strangely, I can repro this in the sandbox vault.

**Comment by mProjectsCode** [comment]
oh yeah.... the new theme
