### ISSUE TITLE
Updating metadata in the 0.4.0 release deletes watched status and date from the metadata

### ISSUE THREAD

**Issue by ltctceplrm** [mProjectsCode/obsidian-media-db-plugin#65]
- [X] The Plugin is up to date
- [X] Obsidian is up to date

**Describe the bug**
When you use the new "update metadata" option in the 0.4.0 release it deletes watched status and date from the metadata.

**To Reproduce**
1. Add a movie using the plugin
2. Change `watched: false `to `watched: true` and add a date for `lastWatched: ""`
3. Press the button to update the metadata
4. `watched:` and `lastWatched:` both disappear

**Expected behavior**
Reloading the information from omdb while retaining watched status and date.

**Occurs on**
- [X] Windows

**Plugin version**
0.4.0

**Additional context**
It looks like the same happens when you choose to update the entire note, it gets recreated without the note content which is expected but it also doesn't add the `watched:` or `lastWatched:` and just seems to skip that.

I hope I'm not a bother by posting a bug so soon after the release, especially since I love the new UI for remapping/excluding metadata.

**Comment by mProjectsCode** [comment]
that is strange, i will take a look at that

**Comment by mProjectsCode** [comment]
> I hope I'm not a bother by posting a bug so soon after the release, especially since I love the new UI for remapping/excluding metadata.

No, issues are always welcome :)
And I am glad that you like the new UI

**Comment by mProjectsCode** [comment]
I have a fix ready, but i will wait a few hours or until tomorrow to test it a bit more.
I don't want to add more bugs xD

**Comment by mProjectsCode** [comment]
fixed in 0.4.1

**Comment by ltctceplrm** [comment]
Thank you, it works great and even works for any other metadata that I've added myself afterwards, this is perfect!
