### ISSUE TITLE
Invalid tag format for YAML Front Matter

### ISSUE THREAD

**Issue by igrybkov** [mProjectsCode/obsidian-media-db-plugin#66]
- [x] The Plugin is up to date
- [x] Obsidian is up to date

**Describe the bug**
Tags in yaml front matter should not include `#` symbol in front of the tag name. And the field `tags:` itself should be array.

According to [documentation](https://help.obsidian.md/How+to/Working+with+tags#Add+tags), to add tag:
> Just type # followed by tag name like #tag1

but for front matter example there's no `#` in front of tags and it is the array:

```
---
tags:
  - tag1
  - tag2
---
```

**Expected behavior**

Tags in yaml front matter should not start with `#`
Valid results should be `tags: ["mediaDB/tv/series"]`

**Occurs on**
- [ ] Windows
- [x] macOS
- [ ] Linux
- [ ] Android
- [x] iOS

**Plugin version**
0.4.0

**Comment by mProjectsCode** [comment]
fixed in 0.4.1
