### ISSUE TITLE
Updating metadata duplicates the open note if it isn't in the default MediaDB folder

### ISSUE THREAD

**Issue by ltctceplrm** [mProjectsCode/obsidian-media-db-plugin#67]
- [X] The Plugin is up to date
- [X] Obsidian is up to date

**Describe the bug**
 When you update metadata in the 0.4.0 release it duplicates the note currently have open if it isn't located in the default folder for new files.

**To Reproduce**
1. Add a movie using the plugin
2. Move it to another folder
3. Press the button to update the metadata
4. The note gets duplicated again in the default folder (with all content intact however)

**Expected behavior**
Ideally it would update the currently open note rather than re-create it with the note content intact.

**Occurs on**
- [X] Windows

**Plugin version**
0.4.0

Edit: The same also happens if you rename the file but the file stays in the default folder.

**Comment by mProjectsCode** [comment]
That is because the plugin expects the note to still be in the media db folder

But I will see, if I can fix this

**Comment by ltctceplrm** [comment]
Oh okay, I usually move the note to Movie Notes or TV Series Notes when I've finished watching it but I realize that's probably not a common workflow. Thank you for looking into it

**Comment by mProjectsCode** [comment]
fixed in 0.4.1

**Comment by ltctceplrm** [comment]
Thank you for fixing this, I really appreciate it
