### ISSUE TITLE
Add Fields to OBDb 

### ISSUE THREAD

**Issue by blu3knight** [mProjectsCode/obsidian-media-db-plugin#68]
**Is your feature request related to a problem? Please describe.**
No problem, but OMDb Offers other data that would be great to bring in. 

**Describe the solution you'd like**
Some fields available in the OMDb API for Movies that could help in creating some interesting searches.

Here are the fields: 

- Actors
- Plot
- Rated

**Comment by mProjectsCode** [comment]
rating is already included, I added actors, but I won't add plot for now.

**Comment by joecan00** [comment]
Please add plot.
