### ISSUE TITLE
Default API enabled

### ISSUE THREAD

**Issue by simzdk** [mProjectsCode/obsidian-media-db-plugin#69]
Is it possible to have a default API enabled if you only use the one all the time? So I dont have to enabled it everytime I create a new entry.

**Comment by mProjectsCode** [comment]
That is implemented as part of #38, I will release those changes in the next week

**Comment by mProjectsCode** [comment]
Issue number 69, nice

**Comment by mProjectsCode** [comment]
> Sorry searched for it, but guess I used the wrong keywords.

No worries, I guess it being closed but not yet released makes is quite easy to miss
