### ISSUE TITLE
BoardGameGeek Data Field - Weight

### ISSUE THREAD

**Issue by discipleofzen** [mProjectsCode/obsidian-media-db-plugin#71]
Ahoi,

I wonder if it is possible to extract one more data field via the Media DB plugin from BoardGameGeek than currently possible. The value I am looking for is the "average weight value" (complexity rating) BoardGameGeek  provides, which is a good indicator for how playable games are with people of varying experience. 

Since I am clearly not capable of extracting this, I would like to encourage you to include this value in the datafields your script extracts. 

I think that at least for regular board game players this value will be of regular interest, so it might be worth the effort.

Best regards, 

DOZ

**Comment by mProjectsCode** [comment]
I have also added more fields to the boardgames

```
        genres: string[];
	onlineRating: number;
	complexityRating: number;
	minPlayers: number;
	maxPlayers: number;
	playtime: string;
	publishers: string[];
	image?: string;

	released: boolean;
```

**Comment by discipleofzen** [comment]
Thank you so very much! :) 

Is it planned to make the updated plugin accessible through the community plugin section of the Obsidian app? The reason I ask is that I'm on unrooted Android, and installing plugins manually doesn't seem easily possible.  

Thanks again and best regards, 

DOZ

**Comment by mProjectsCode** [comment]
yes, within the next few days. I want to test a bit more before I release the update, so that I don't accidentally break something
