### ISSUE TITLE
"Movie not found!" error when using "Create Media DB Entry (Game)" option

### ISSUE THREAD

**Issue by iznaut** [mProjectsCode/obsidian-media-db-plugin#77]
-   [X] The Plugin is up to date
-   [X] Obsidian is up to date

**Describe the bug**
Creating a media entry with the (Game) option has inconsistent results - sometimes it will return an error message from OMDbAPI, even though searching the same title with the advanced search will yield SteamAPI results.

**To Reproduce**

1. Select "Create Media DB Entry (Game)" from the Command Palette
2. Enter "neon white" and hit "Ok"

The plugin will return an OMDbAPI error "Movie not found!"

**Expected behavior**
Searching "Neon White" should return SteamAPI results. The same query with _only_ the SteamAPI option enabled in the advanced search will work, but it will fail if the OMDbAPI option is also enabled.

**Screenshots**
<img width="590" alt="Screenshot 2022-12-17 at 7 39 52 PM" src="https://user-images.githubusercontent.com/36773942/208552354-8e7f9bac-d653-4102-8d39-0b50987c7ca5.png">
<img width="324" alt="Screenshot 2022-12-17 at 7 39 58 PM" src="https://user-images.githubusercontent.com/36773942/208552355-a856653a-66a2-44e0-acd4-03c6fa2bcf85.png">
<img width="573" alt="Screenshot 2022-12-19 at 6 23 58 PM" src="https://user-images.githubusercontent.com/36773942/208553284-8dee3eab-1330-46fd-95f5-2b1764d8a986.png">
<img width="577" alt="Screenshot 2022-12-19 at 6 24 05 PM" src="https://user-images.githubusercontent.com/36773942/208553286-89020986-2a41-47af-895c-08164ddd5c2f.png">

**Occurs on**

-   [ ] Windows
-   [X] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.5.0

**Comment by mProjectsCode** [comment]
Thanks for the report, it seems like OMDb returns an error if the item can't be found.
I will fix this if I can find some free time during Christmas and New Year vacation.

**Comment by mProjectsCode** [comment]
Finally found some time
