### ISSUE TITLE
Question regarding bulk import

### ISSUE THREAD

**Issue by yte424** [mProjectsCode/obsidian-media-db-plugin#79]
-   [x ] The Plugin is up to date
-   [x ] Obsidian is up to date

**Describe the bug**
Question regarding bulk import
# MDB - bulk import error report 12-23-2022 12-42-10

| file                                       | error                                      |
| ------------------------------------------ | ------------------------------------------ |
| Media DB/music/import/metadata.json        | metadata field 'titles' not found or empty |
| Media DB/music/import/AlbumsToListento.csv | metadata field 'titles' not found or empty |

can you give me a hint what I am doing wrong? 

Thanks in advance

**To Reproduce**
Steps to reproduce the behavior

I try to use the bulk imoport with this csv file:

![CSV file to import](https://user-images.githubusercontent.com/6085438/209332040-5915da94-ab1d-453e-bc45-76fc6638d3a9.png)

than I added a metadata.json file. Don't know if this is needed:
![Metadata json](https://user-images.githubusercontent.com/6085438/209332096-12478464-b00a-4a25-9042-951757013d84.png)

And I choose the following option in the import: 
![[Import Options.png]]
![Import Options](https://user-images.githubusercontent.com/6085438/209332137-e89dcea0-21a7-43dc-8cca-9421728358f2.png)

And I alway get an error message from the import. 

**Expected behavior**

**Screenshots**

**Occurs on**

-   [x ] Windows
-   [ ] macOS
-   [ ] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.5.0

**Additional context**

**Comment by mProjectsCode** [comment]
Bulk import expects the files in the folder to already represent the media db notes you want to have in the end. 

The Bulk import will go through the folder and for each file, search for the metadata field specified, then query the selected API with the content of that field and finally update the contents of the file with the data it received from the API.
