### ISSUE TITLE
Option to auto-switch to newly added note

### ISSUE THREAD

**Issue by iznaut** [mProjectsCode/obsidian-media-db-plugin#82]
**Is your feature request related to a problem? Please describe.**
It's pretty common for me to want to make edits to a Media DB entry shortly after adding it. My current solution is a Datatable query that returns the most recently created notes, so I open that note and click the topmost entry.

**Describe the solution you'd like**
A toggle in settings to automatically switch to the newly created Media DB note after the prompt closes.

**Comment by kelszo** [comment]
Already done in #128. Is released in the latest version of the plugin.
