### ISSUE TITLE
Board Game Folder path is not set as path entry

### ISSUE THREAD

**Issue by AmCzzZ** [mProjectsCode/obsidian-media-db-plugin#85]
The entry box for Board Game Folder is set as the template list, instead of the folder list.

**Comment by mProjectsCode** [comment]
I have no idea, what you mean. Could you describe your problem in more detail?

**Comment by mProjectsCode** [comment]
Yeah, I somehow put a filesuggester there but there should be a foldersuggester. You should be able to ender a folder path manually, just the suggestions are wrong, until i fix the issue.

**Comment by mProjectsCode** [comment]
fixed and will be added in the next release
