### ISSUE TITLE
Plugin throws error if it can't find a game in the OMDB

### ISSUE THREAD

**Issue by FelixBrakel** [mProjectsCode/obsidian-media-db-plugin#86]
-   [x] The Plugin is up to date
-   [x] Obsidian is up to date

**Describe the bug**
If a game isn't in the OMDB, but it is on Steam, the plugin will fail to find it on OMDB and throw an error instead of returning the results from Steam

**To Reproduce**
 - Make sure the OMDB API key is set up
 - Execute the "Create MediaDB entry (Game)" command
 - Search Citizen Sleeper

**Expected behavior**
An overview of the results from Steam. Doing an advanced search and only looking through Steam does yield the correct results.

**Screenshots**

**Occurs on**

-   [ ] Windows
-   [ ] macOS
-   [x] Linux
-   [ ] Android
-   [ ] iOS

**Plugin version**
0.5.0

**Comment by FelixBrakel** [comment]
Looks like this was fixed with the latest commit actually but the plugin version hasn't been bumped yet so installing the plugin through obsidian still installs the version without the fix.

**Comment by mProjectsCode** [comment]
I still need to test it before I release it and I am currently taking a break to focus on my exams.

**Comment by StephBoyardee** [comment]
Hey am I missing something? I tried using the OMDB search, but every time I just get an "Error: MDB | Authentication for OMDbAPI failed. Check the API key." error. I didn't see anything mentioned in the readme for making an API key, and the other database searches work fine. This is on both mobile and desktop

**Comment by mProjectsCode** [comment]
> Hey am I missing something? I tried using the OMDB search, but every time I just get an "Error: MDB | Authentication for OMDbAPI failed. Check the API key." error. I didn't see anything mentioned in the readme for making an API key, and the other database searches work fine. This is on both mobile and desktop

Look in the readme under supported APIs. There is a setting in the plugins setting Page for the api key.
