### ISSUE TITLE
Any plans on adding Manga as another media?

### ISSUE THREAD

**Issue by nhemarron** [mProjectsCode/obsidian-media-db-plugin#87]
Your Plugin is amazing, do you plan to add another feature for Manga?

I know there is booksearch but it isn't suited for manga series.

Would highly appreciate or even support with some money, regarding the effort necessary 

best regards, keep up the good work !

**Comment by mProjectsCode** [comment]
I am currently taking a break from programming to focus on my exams, but i should be able to do this towards the beginning of next month.

**Comment by nhemarron** [comment]
Good luck with your exams :) take your time

If you have some Ko-Fi or anything familiar I'd like to show my appreciation with small kind of  support for your effort already.
The Plugin is amazing in so many regards.

**Comment by mProjectsCode** [comment]
> If you have some Ko-Fi or anything familiar I'd like to show my appreciation with small kind of support for your effort already.
> The Plugin is amazing in so many regards.

Thanks for wanting to support me. :)
I looked at setting up a way for people to support me financially through things like github sponsors, but at the scale of my projects, the german tax laws make this more trouble than it is worth.

**Comment by mProjectsCode** [comment]
Done in this PR.
https://github.com/mProjectsCode/obsidian-media-db-plugin/pull/99
