### ISSUE TITLE
Add director and writer to metadata field options

### ISSUE THREAD

**Issue by adamehunt** [mProjectsCode/obsidian-media-db-plugin#89]
**Is your feature request related to a problem? Please describe.**
I would like to query all movies by a certain director or writer.

**Describe the solution you'd like**
Please add "director" and "writer" to the MediaDB Movie metadata field options.

**Additional context**

**Comment by ltctceplrm** [comment]
The name of the director is actually already added but it's labeled as the producer, you can remap producer to director.
Having the writer would be great to have as well

**Comment by mariomui** [comment]
i would love the ability to get the writer as well.

**Comment by FCalleja** [comment]
Another +1 to being able to get Director and Writer for TV and Movies

**Comment by ltctceplrm** [comment]
Both of these were added in 0.60  so this issue can be closed as well
