### ISSUE TITLE
Toggle on/off default front matter for Custom Templates

### ISSUE THREAD

**Issue by thisisgonnatakeawhile** [mProjectsCode/obsidian-media-db-plugin#91]
Hi peeps,

I was wondering if it'd be possible to have a quick toggle for the Custom Template feature which could enable or disable the default front matter on new custom templated notes. 

It'd be great if our own Custom Templates could also include our own custom front matter without needing to set all Property Mappings to 'remove'.

Thanks!

P.S: If this behaviour is already a feature and I have overlooked it, please excuse my ignorance.

**Comment by kelszo** [comment]
+1 for this. Should be handled how the original [Obsidian Book Search Plugin](https://github.com/anpigon/obsidian-book-search-plugin) does it.

I.e. the user specifies a path for a template and the plugin uses that template without inserting it's own frontmatter.

Is this plugin still being developed? I would have no problem creating a pull request fixing this if I can get a thumbs up from someone with merging capabilities.

**Comment by mProjectsCode** [comment]
sure, I am just a bit busy atm and because of that only fixed major bugs.

if you create a PR for this then please make the feature an optional toggle and keep the current default behavior.

**Comment by mProjectsCode** [comment]
you can change that to show the file path if you want. I don't think there was a reason why one shows the file name.
