### ISSUE TITLE
Custom frontmatter

### ISSUE THREAD

**Issue by sascha-andres** [mProjectsCode/obsidian-media-db-plugin#92]
**Is your feature request related to a problem? Please describe.**
I previously used a template and switched to MediaDB plugin. Great work. What is now lost. though, is the banner.

**Describe the solution you'd like**
Ability to add custom fields to the front matter

**Comment by sascha-andres** [comment]
May go well along with #91

**Comment by mProjectsCode** [comment]
You can already do so by specifying a template, that has your custom front matter, in the plugin settings. On note creation, the frontmatter of the template is then merged with the new queried frontmatter.

**Comment by sascha-andres** [comment]
> You can already do so by specifying a template, that has your custom front matter, in the plugin settings. On note creation, the frontmatter of the template is then merged with the new queried frontmatter.

Thanks.
