### ISSUE TITLE
OMDbAPI error

### ISSUE THREAD

**Issue by smriti010305** [mProjectsCode/obsidian-media-db-plugin#96]
-   [ ] The Plugin is up to date
-   [ ] Obsidian is up to date

**Description**
I am a new Obsidian user trying to use it for media tracking. Whenever I try to use the plugin to search for movies, it gives an error saying "Authentication failed. Check API"

**Expected behavior**
I would like for the plugin to work as expected so that I can use it for media tracking

**Screenshots**
<img width="480" alt="image" src="https://github.com/mProjectsCode/obsidian-media-db-plugin/assets/129586221/5c4082f8-1227-46ba-b87c-f5bfc9f3fa63">

**Occurs on**
-   [ ] Windows 10

**Plugin version**
0.5.2

**Comment by mProjectsCode** [comment]
You need an API key for OMDb, as detailed in the readme [here](https://github.com/mProjectsCode/obsidian-media-db-plugin#currently-supported-apis).

**Comment by mProjectsCode** [comment]
You enter that API key into the plugins settings page.
